### ISSUE TITLE
ImportMesh imports mesh as a 3D surface mesh

### ISSUE THREAD

**Issue by Lekicafem** [c3m-labs/ImportMesh#4]
I got a suggestion to inform you that the mesh imported by ImportMesh is not correct. It imports this mesh as a 3D surface mesh - which is not what we want. I send you the file so that you can fix the import.

![meshissue](https://user-images.githubusercontent.com/55095622/64960291-54711500-d893-11e9-9edb-f5f85d7e0ccb.jpg)

**Comment by PintarM** [comment]
Thank you @Lekicafem for reporting this issue. :)

Actually your example works as expected and resulting `ElementMesh` contains only `"BoundaryElements"`. This is because input file (I found it in your repository.) contains line `*ELEMENT, TYPE=S8R`, which indicates that shell elements should be used and they are embedded in 3D space.

One workaround is to change Abaqus element type from `S8R` to `CPE8` or something similar (2D plane strain elements). 

Other workaround is to remove third coordinate from nodes and assign `"BoundaryElements"` as `"MeshElements"`.

```mathematica
Needs["ImportMesh`"]
bmesh = ImportMesh["path_to_file\\meshcurvedshape.inp"]

mesh = ToElementMesh[
  "Coordinates" -> bmesh["Coordinates"][[All, {1, 2}]],
  "MeshElements" -> bmesh["BoundaryElements"]
]
```

**Comment by Lekicafem** [comment]
You're welcome, and thank you.


On Mon, 16 Sep 2019 12:14:06 -0700
  PintarM <notifications@github.com> wrote:
> Thank you @Lekicafem for reporting this issue. :)
> 
> Actually your example works as expected and resulting 
>`ElementMesh` contains only `"BoundaryElements"`. This is 
>because input file (I found it in your repository.) 
>contains line `*ELEMENT, TYPE=S8R`, which indicates that 
>shell elements should be used and they are embedded in 3D 
>space.
> 
> One workaround is to change Abaqus element type from 
>`S8R` to `CPE8` or something similar (2D plane strain 
>elements). 
> 
> Other workaround is to remove third coordinate from 
>nodes and assign `"BoundaryElements"` as 
>`"MeshElements"`.
> 
> ```mathematica
> Needs["ImportMesh`"]
> bmesh = ImportMesh["path_to_file\\meshcurvedshape.inp"]
> 
> mesh = ToElementMesh[
>  "Coordinates" -> bmesh["Coordinates"][[All, {1, 2}]],
>  "MeshElements" -> bmesh["BoundaryElements"]
> ]
> ``` 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/c3m-labs/ImportMesh/issues/4#issuecomment-531917645

Mit freundlichen Grüßen,

Lejla Selimovic

--------------------------------------

Lejla Selimovic, M. Sc. Doktorandin

Institut für Mathematik

Technische Universität Clausthal

Erzstrasse 1

D - 38678 Clausthal-Zellerfeld

Raum: 317

Telefon: 05323 / 72-2408


e-mail: lejla.selimovic@tu-clausthal.de
