### ISSUE TITLE
ImportMesh::eltype: Element type B31 is not supported.

### ISSUE THREAD

**Issue by asdasdqwdqwfsdf** [c3m-labs/ImportMesh#5]
I have found this Abaqus Inp file (**Beams.inp**) error:
```
ImportMesh::fail: Failed to extract mesh from F:\ImportMesh\Tests\Abaqus\Beams.inp

ImportMesh::eltype: Element type B31 is not supported.
```

**Comment by PintarM** [comment]
Thank you for your notification.

This behavior is expected because beam type of element (in Abaqus type "B31") is not supported in Mathematica and therefore mesh cannot be imported. That is why an example of such file is also included in folder with test input, to check if the import process fails in controlled manner.
